<?php

namespace Tiziano\MovieNetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('titolo' => 'ASC'));
    }

	public function findOneByIdJoined($id)
	{
	    $query = $this->getEntityManager()
	        ->createQuery('
	            SELECT m, g, r FROM TizianoMovieNetBundle:Movie m
	            LEFT JOIN m.genere g
	            LEFT JOIN m.regista r
	            WHERE m.id = :id'
	        )->setParameter('id', $id);

	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}    
}
